name: SEO Audit Generation Backend Build and Test

on:
  workflow_dispatch:
  push:
    paths:
        - 'backend/**'

jobs:
    build-test:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            
            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                    node-version: '25'

            - name: Install dependencies
              working-directory: backend
              run: npm ci
            
            - name: Run tests (If any)
              working-directory: backend
              run: npm test --if-present
